<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-BidCommerce-0d20b4fa-b37a-4dc2-8bf0-286964bfb641</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Views\Shared\_ChatWidget.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Views\Shared\_ChatWidget.cshtml" />
    <_ContentIncludedByDefault Remove="wwwroot\css\login-account.css" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.41" />
    <PackageReference Include="Stripe.net" Version="48.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\products\" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Views\Shared\_ChatWidget.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Views\Shared\_ChatWidget.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RateLimiterLib">
      <HintPath>..\..\..\..\RiderProjects\RateLimiterLib\RateLimiterLib\bin\Debug\net8.0\RateLimiterLib.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
